In [2]:
import numpy as n

In [3]:
my_list = [10,20,30]

In [4]:
type(my_list)

list

In [5]:
np_my_array = np.array(my_list)

In [6]:
type(np_my_array)

numpy.ndarray

In [7]:
np_my_array.max()

np.int64(30)

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.random.random(3)

array([0.02418465, 0.54598232, 0.4409979 ])

In [10]:
# array arithmetic

In [11]:
my_list1 = [1,2]

In [12]:
my_list2 = [2,3]

In [13]:
my_list1 + my_list2

[1, 2, 2, 3]

In [15]:
np_array1 = np.array(my_list1)

In [17]:
np_array2 = np.array(my_list2)

In [18]:
np_array1 + np_array2

array([3, 5])

In [19]:
np_array1 * np_array2

array([2, 6])

In [20]:
np_array1 - np_array2

array([-1, -1])

In [23]:
np_array1 * 5
# dizinin değerlerini 5 ile çarpıyor

array([ 5, 10])

In [24]:
my_list1 * 5
# listeyi 5 defa yazıyor

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [26]:
other_array = np.array([20,40,30,10,50])

In [27]:
other_array.min()

np.int64(10)

In [28]:
other_array.sum()

np.int64(150)

In [31]:
# other_array * np_array_1
# hata verir çünkü broadcasting kuralından dolayı.diziler eşit sayıda indekse  sahip olmalı ya da tek bir sayıyla çarpılmalı

# arrange & index

In [34]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [35]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np_array = np.arange(0,15)

In [39]:
np_array[0]

np.int64(0)

In [42]:
np_array[1:6]

array([1, 2, 3, 4, 5])

In [43]:
np_array[::-1]

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

# random

In [44]:
np.random.randn(4)

array([ 0.165885  , -1.08338464, -1.19536873, -0.91929716])

In [45]:
np.random.randn(4,4)

array([[ 0.44772141,  0.94642901, -0.89986323, -0.6880159 ],
       [ 0.65865751, -0.29004175, -2.21657805,  1.26953149],
       [ 1.67228255, -0.05629661,  1.40003668,  0.29807803],
       [-1.69413095, -1.41217347,  0.53789088,  0.02031018]])

In [50]:
np.random.randint(1,500,6)
# 1'den 500'e kadar olan sayılardan rastgele 6 tanesini seçiyor

array([495, 463,  19,   3, 199, 141], dtype=int32)